# Generated by Django 4.2 on 2023-04-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdProdCat', models.CharField(max_length=200, unique=True)),
                ('Designation', models.CharField(max_length=200, unique=True)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='unit_measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUnitMes', models.CharField(max_length=200, unique=True)),
                ('Designation', models.CharField(max_length=200)),
                ('lotQuantity', models.FloatField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProd', models.CharField(max_length=200, unique=True)),
                ('Designation', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Price', models.FloatField()),
                ('QtAlert', models.FloatField()),
                ('Desciption', models.TextField(max_length=500)),
                ('IdProdCat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resto.product_categorie')),
                ('IdUniteMes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resto.unit_measure')),
            ],
        ),
    ]
